s = input('Type anything: ')
snum = s.isnumeric()
salp = s.isalpha()
salnum = s.isalnum()
sup = s.isupper()
slo = s.islower()
print('Value type: {}'.format(type(s)))
print('This value is numeric? {}'.format(snum))
print('This value is alpha? {}'.format(salp))
print('This value is alphanumeric? {}'.format(salnum))
print('This value is uppercase? {}'.format(sup))
print('This value is lowercase? {}'.format(slo))
